project:
  type: book

book:
  title: "learning diary"
  author: "Zihan Liu"
  date: "2024/1/23"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - week_3.qmd
    - week_4.qmd
    - week_6.qmd
    - week_7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

