---
title: "week_4"
author: "Zihan Liu"
---
# Jakarta city challenge
## Flood
Flood-prone Jakarta is the world’s fastest sinking city — as fast as 10 centimetres per year. In parts of North Jakarta, which is particularly susceptible to flooding, the ground has sunk 2.5 metres in 10 years. Excessive extraction of groundwater for drinking and commercial use is largely responsible for this: When water is pumped out of an underground aquifer, the land above it sinks 
Source from: https://www.channelnewsasia.com/cnainsider/why-jakarta-is-world-fastest-sinking-city-floods-climate-change-781491

## City sinking
With global temperatures rising and ice sheets melting, plenty of coastal cities face a growing risk of flooding due to sea level rise. Few places, however, face challenges like those in front of the Jakarta metropolitan area. In recent decades, Jakarta flooding problems have grown even worse, driven partly by widespread pumping of groundwater that has caused the land to sink, or subside, at rapid rates. By some estimates, as much as 40 percent of the city now sits below sea level. There are signs showing that rainstorms are getting more intense as the atmosphere heats up, damaging floods have become commonplace.

The picture below shows The Landsat images above show the evolution of the city over the past three decades. The widespread replacement of forests and other vegetation with impervious surfaces in inland areas along the Ciliwung and Cisadane rivers has reduced how much water the landscape can absorb, contributing to runoff and flash floods.

# Policy goal

In September 2022, the Jakarta Environmental Agency introduced a Strategy for Air Pollution Control (SPPU), which included more than 70 action plans to improve air quality. Focusing on 1) governing air pollution controls, 2) reducing emissions from mobile sources, and 3) reducing emissions from stationary sources.
 
# The actions we can do

## Water management to reduce groundwater extraction

Implementing effective water management to reduce groundwater extraction can align with sustainable urban development goals. As the widespread pumping of groundwater is the human factor of sinking and flooding, it is necessary to pretend residents from doing it and worsen the situation.

## Add more green plants to improve the environment

Investing in green infrastructure, can mitigate sinking and enhance urban resilience, aligning with global climate action and sustainable city planning. It is obvious from the picture before that the greenery has been replaced by city land.

Here are benefits from greenery. rain hits the ground at higher speeds where there is a lack of tree cover. A canopy of leaves, branches and trunks slows down the rain before it hits the ground simply by getting in the way. In addition, root systems help water penetrate deeper into the soil at a faster rate under and around trees.

https://www.woodlandtrust.org.uk/trees-woods-and-wildlife/british-trees/flooding/

## Reduce emission

Jakarta was again ranked the most polluted city in the world by Swiss technology company IQAir in 2023. Transport is a very important source of Jakarta’s Pollution while  Industry and Power Plants Are Also Contributors。 In September 2022, the Jakarta Environmental Agency introduced a Strategy for Air Pollution Control (SPPU), which included more than 70 action plans to improve air quality. Focusing on 1) governing air pollution controls, 2) reducing emissions from mobile sources, and 3) reducing emissions from stationary sources.
Source from:
https://urban-links.org/insight/7-things-to-know-about-jakartas-air-pollution-crisis/

Warmer temperatures caused by pollution could lead to the ground swelling and expanding upwards by up to 12mm (0.5 inches) and the ground could sink downwards, beneath the weight of a building, by as much as 8mm (0.3 inches).

Source from:
https://news.sky.com/story/chicago-underground-climate-change-is-deforming-land-under-buildings-and-things-are-sinking-says-study-12923119

# To manage the emission using remotely sensed data

## NO2 and CO2 monitoring
Use data from NO2 from https://energyandcleanair.org/ , there are before and after maps that we can decide the time period and the highly polluted areas are shown in red. CO2 can be found from our world in data and the analysis should be in python.

## Vegetation Mapping and Monitoring

To manage the pollution, greenery is an indirect method. Satellite and aerial imagery provide detailed information on vegetation cover, allowing for the assessment of the extent and health of greenery across large areas. This helps in tracking changes over time, such as the growth or decline of forests, parks, and urban green spaces.

# Link with global agendas / goals

Sustainable Development Goals (SDGs): Particularly relevant are SDG 11 (Sustainable Cities and Communities), SDG 13 (Climate Action), and SDG 15 (Life on Land).  Addressing Jakarta's issues contributes to creating sustainable and resilient cities, taking urgent action to manage climate change and its impacts, and managing forests and combating desertification, halting and reversing land degradation, and halting biodiversity loss.

New Urban Agenda: This agenda emphasizes the need for cities to be inclusive, safe, resilient, and sustainable.  By addressing its sinking and flooding issues, Jakarta works towards creating a more inclusive urban environment, ensuring safety and resilience for all its inhabitants.

# Advances of current local, national or global approaches.

Jakarta may set a practical example for sustainable urban development. By addressing issues related to flood, land subsidence and sea-level rise, Jakarta contributes to global efforts in climate change mitigation, providing a case study for coastal city management under climate threats. Jakarta’s initiatives align with the SDGs, demonstrating how urban areas can deal with complex challenges like rapid urbanization, climate change, and greenery lose in an integrated manner.

# Reflection

My research revealed plenty of existing strategies addressing urban challenges;     however, it seemed like many straightforward, sensible solutions are often overlooked by local governments. For Jakarta, the issue isn't just about addressing the immediate impacts of these problems but also about considering long-term, sustainable solutions.

While exploring Jakarta's situation, I noticed a tendency for short-term, reactive measures rather than long-term systemic changes.  For instance, the focus has often been on building sea walls or improving drainage, which, although necessary, failed to manage the root causes such as excessive groundwater extraction and less comprehensive urban planning.

Jakarta requires comprehensive urban planning that considers environmental sustainability, infrastructure resilience, and community safe water.	 



